<?php
    // Set at 86,400 seconds, allows the user to browse your application for 24 hours before needing to re-authenticate their session.
    ini_set('session.gc_maxlifetime', 86400);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Database</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    <!-- Use the following stylesheet during development -->
    <!-- It is generated by the gulp task devStyles -->
    <link rel="stylesheet" href="../css/build/main.prefixd.css">
    
    <!-- Use the following stylesheet for production -->
    <!-- It is also generated by the gulp task devStyles -->
    <!-- <link rel="stylesheet" href="../css/build/main.min.css"> -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript" src="../js/main.js"></script>

    <!--script type="text/javascript">
        // Initialize collapse button
        $(".button-collapse").sideNav({
          menuWidth: 300, // Default is 240
          edge: 'right', // Choose the horizontal origin
          closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
        });
    </script-->

</head>
<body class="content">